### ISSUE TITLE
Support for jupyterlab 2.x

### ISSUE THREAD

**Issue by nibheis** [osscar-org/widget-code-input#8]
Hi!

Does this widget support jupyterlab 2.x?
I'm planning to move Noto to JL 2.

Best regards,
Pierre-Olivier

**Comment by dou-du** [comment]
Very sorry for late reply. Just see this issue.  Yes, this is working for Jupyterlab 2.x.
I am planning to update this for JupyterLab 3.x soon. 

One more thing I would mention is that this widget has some potential security risk.
From the widget, it allows to execute any Python code. For example, "os.system("rm -rf")".
We stopped to use it for our web apps (with voila) due to this reason. 

Dou
